### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by wdelfuego** [vgocoder/docker-compose-laravel-alpine-for-mac-m1#2]
Hi, thanks for preparing this repo!

I'm trying to get things to work under MacOS Monterey 12.0.1, but it's not working for me.

I've followed all the steps outlined in the readme and can see all four containers (mysql, redis, php and nginx) up and running in Docker Desktop. I can connect over CLI to all four of them without a problem, but I run into these issues:

1. To test, I have placed my own index.html file in /wwwroot, but when I surf to http://localhost/, I get a generic 'Welcome to nginx!' page instead of the code I placed into /wwwroot. I placed the files in /wwwroot on the host machine, not within the container. I'd expect nginx to pick that up but I might be missing something.
2. The docker-compose file indicates that the nginx container also exposes ports 443, 8000 and 8080, but when I surf to those my browser complains that the server dropped the connection (I am guessing this might be expected behavior)
3. When I try to connect to the MySQL server using Sequel Ace, using 127.0.0.1 as server and 3306 as the port, I can't establish the connection. The message I get is: _Host '172.18.0.1' is not allowed to connect to this MySQL server_. I don't understand where that IP address comes from and why I can't connect to the MySQL database from my host system; I'm assuming that the post is exposed for that reason but maybe I'm misunderstanding.

I am probably running into these issues due to a lack of knowledge, if you could tell me how to proceed to get this working that'd be awesome. I'd be glad to supply further details if required.

Thanks!

**Comment by wdelfuego** [comment]
With regard to the first point, I now understand that a little nginx config is required to get a dev environment going. Without changing or adding anything else, I've mapped demo.local to 127.0.0.1 on my host machine and placed an index.html file in /wwwroot/demo/public, and I now get that file served on demo.local, that's great :)

However if I replace the index.html with an index.php file, I get an nginx error: "An error occurred. Sorry, the page you are looking for is currently unavailable. Please try again later.". No info is added to any log files in /nginx/log. The nginx environment seems unable to use the php container on port 9000, even though that container is up and accessible through cli. 

If you have any clues, that'd be great!

**Comment by vgocoder** [comment]
please replace the nginx conf section like this 

```
location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass   php:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
```
